import { useState } from 'react';
import type { RLCParameters } from '../math/rlcParameters';
import { classifyFixedPoint } from '../math/stability';
import { formatNumber } from '../components/MetricCard';
export function TraceDeterminantPlot({ m }: { m: RLCParameters }) {
  const [hover, setHover] = useState<{ tau: number; delta: number } | null>(null);
  const tauMax = Math.max(3 * m.omega0!, 1.15 * Math.abs(m.tau!)), deltaMax = Math.max(2.5 * m.delta!, tauMax * tauMax / 4 * 1.15);
  const X = (tau: number) => 380 + 295 * tau / tauMax, Y = (delta: number) => 325 - 270 * delta / deltaMax;
  const parabola = Array.from({ length: 101 }, (_, i) => { const t = -tauMax + 2 * tauMax * i / 100; return `${i === 0 ? 'M' : 'L'}${X(t)},${Y(t * t / 4)}`; }).join(' ');
  const hoverPoint = (e: React.PointerEvent<SVGSVGElement>) => { const rect=e.currentTarget.getBoundingClientRect(), x=(e.clientX-rect.left)*760/rect.width, y=(e.clientY-rect.top)*430/rect.height; if(x>=85&&x<=675&&y>=55&&y<=395)setHover({tau:(x-380)*tauMax/295,delta:(325-y)*deltaMax/270}); else setHover(null); };
  return <div><svg viewBox="0 0 760 430" className="trace-diagram" role="img" aria-label="Диаграмма след–детерминант с текущей точкой RLC" onPointerMove={hoverPoint} onPointerLeave={()=>setHover(null)}><rect x="85" y="55" width="590" height="270" fill="#eef5f4"/><rect x="85" y="325" width="590" height="70" fill="#fbefeb"/><path d={`${parabola} L675,325 L85,325Z`} fill="#f3f1e9"/><path d="M85 325H696M380 402V38" stroke="#405d67" strokeWidth="1.5"/><path d={parabola} fill="none" stroke="#b66535" strokeWidth="2"/><path d="M380 55V325" stroke="#3d8b7b" strokeWidth="3"/><g fontSize="15" fill="#334b55" textAnchor="middle"><text x="215" y="88">Устойчивая спираль</text><text x="545" y="88">Неустойчивая спираль</text><text x="220" y="299">Устойчивый узел</text><text x="544" y="299">Неустойчивый узел</text><text x="380" y="372">Седло · Δ &lt; 0</text><text x="415" y="160" textAnchor="start" fill="#3d8b7b">Центр</text><text x="570" y="156" fill="#b66535">D = 0: Δ = τ²/4</text><text x="714" y="329">τ, с⁻¹</text><text x="393" y="27" textAnchor="start">Δ, с⁻²</text><text x="366" y="346">0</text><text x="85" y="422">−{formatNumber(tauMax,3)}</text><text x="675" y="422">{formatNumber(tauMax,3)}</text><text x="76" y="60" textAnchor="end">{formatNumber(deltaMax,3)}</text></g><path d={`M${X(m.tau!)} ${Y(m.delta!)}H380`} stroke="#174a60" strokeDasharray="5 5"/><circle cx={X(m.tau!)} cy={Y(m.delta!)} r="7" fill="#174a60" stroke="white" strokeWidth="2"><title>τ = {m.tau}; Δ = {m.delta}; {m.fixedPointType}</title></circle><text x={X(m.tau!)+11} y={Y(m.delta!)-10} fontSize="14" fill="#174a60">RLC</text>{hover&&<circle cx={X(hover.tau)} cy={Y(hover.delta)} r="4" fill="#b66535"/>}</svg><p className="caption">{hover ? `τ = ${formatNumber(hover.tau)} с⁻¹; Δ = ${formatNumber(hover.delta)} с⁻² → ${classifyFixedPoint(hover.tau,hover.delta)}` : 'Наведите указатель на диаграмму для классификации. Точка RLC связана с параметрами контура; масштаб осей адаптируется.'}</p></div>;
}
